# -*- coding: utf-8 -*-
"""project_morze.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MzMAcPy3ajZyL7Ya2z9l5zzvpoMOb8g_
"""

import random

list_of_words = [
    "cat",
    "dog",
    "mouse",
    "leon",
    "lacoste",
    "beaver",
    "princess"
]
"""Cписок английских слов и фраз, которые будем расшифровывать."""

morze_alphabet = {
  "a": ".-",
  "b": "-...",
  "c": "-.-.",
  "d": "-..",
  "e": ".",
  "f": "..-.",
  "g": "--.",
  "h": "....",
  "i": "..",
  "j": ".---",
  "k": "-.-",
  "l": ".-..",
  "m": "--",
  "n": "-.",
  "o": "---",
  "p": ".--.",
  "q": "--.-",
  "r": ".-.",
  "s": "...",
  "t": "-",
  "u": "..-",
  "v": "...-",
  "w": ".--",
  "x": "-..-",
  "y": "-.--",
  "z": "--..",
}
"""Словарь Морзе."""

def morse_encode(word):
  english_to_morze = ""
  for i in word:
    english_to_morze += morze_alphabet[i]+" "
  return(english_to_morze)
"""Шаг 1. Функция morse_encode(word), 
которая переводит слова на английском языке 
в последовательности точек и тирe."""

def get_word():
    return(random.choice(list_of_words))
"""Шаг 2. Функция get_word(), которая получает 
случайное слово из списка.
"""

def different_case(word):
  return(word.lower().replace(" ", ""))
"""
Шаг 8. Определим обработку слов с пробелами и разного регистра.
"""

answers = []
def print_statistics(answers):
  print(f"Всего задачек: {len(answers)}")
  print(f"Отвечено верно: {answers.count(True)}")
  print(f"Отвечено неверно: {answers.count(False)}")
"""
Шаг 3. Создайте в начале программы список answers = []. 
Напишите функцию print_statistics(answers), 
которая на основе списка answers типа [True, False, False, True, False] 
выводит статистику типа:
Всего задачек: 5
Отвечено верно: 2
Отвечено неверно: 3
"""

def main():
  name_of_gamer = input("Добро пожаловать в игру!\nВведите имя\n").capitalize() ##Запоминаем имя с большой буквы, даже если пользователь допустил ошибку
  print(f"Привет, {name_of_gamer}!\nИгра начинается!\nНажмите Enter чтобы начать")
  input()
  while 1:
    random_word = get_word()
    print(f"Слово {len(answers)+1} - {morse_encode(random_word)}")
    input_word = different_case(input())                                        ##сразу приведем слово в порядок (регистр и лишние пробелы)
    if random_word == input_word:
      print(f"Верно, {random_word}. ")
      answers.append(True)
    elif input_word == "stop":
      break
    else:
      print(f"Неверно, {random_word}!")
      answers.append(False)
"""
Шаг 4. Старт программы
"""
main()
"""
Шаг 6. Выводим статистику с помощью вызова ранее написанной функции
"""
print_statistics(answers)

